# Generated by Django 4.2.5 on 2023-10-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Vegetables'), (2, 'Fruits'), (3, 'Grocery')], verbose_name='Category'),
        ),
    ]
